### PR TITLE
list Cleanup the list layout and fonts

### PR DESCRIPTION
**Pull request by ghelton**

### CODE REVIEW

**Comment by ghelton** [comment]
Added new fonts and fixed up colors, also submitting built code
screen shot 2016-02-15 at 12 43 19 pm

**Comment by troyconquer** [comment]
hey @astrism , was it too hard to expand "pts" to the same width as "25" ? like it is in designs.

**Comment by troyconquer** [comment]
otherwise it is :+1:

**Comment by ghelton** [comment]
@troyconquer I fixed the sizing

**Pull request merged**
